// Mock tiles for the /dev/tiles verification page (DEV-only — never bundled
// into production; see App.tsx lazy import). Covers every status the tile
// renders so the visual critic can check all states in one screen.

import type { TileSession } from './types'

const claudeBoot = (task: string): string[] => [
  '● Read package.json (1 file)',
  `● ${task}`,
  '',
  '  Let me start by exploring the codebase structure to',
  '  understand how the existing modules fit together.',
  '',
  '● Bash(bun run build)',
  '  ⎿ tsc -b && vite build',
  '     ✓ 2243 modules transformed.',
  '     ✓ built in 245ms',
]

const shellTail = (cmd: string): string[] => [
  `$ ${cmd}`,
  'Compiling amux-server v3.0.0',
  '   Compiling tokio v1.40.0',
  '   Compiling axum v0.7.5',
  '    Finished `release` profile [optimized]',
  '     Running `target/release/amux-server`',
  'listening on 127.0.0.1:8823',
]

export const MOCK_TILES: TileSession[] = [
  {
    name: 'gel-astro',
    task_summary: 'Wire the SSE delta merge into the sessions cache',
    status: 'active',
    dir: '/opt/projects/gel',
    provider: 'claude',
    tokens: 48200,
    branch: 'feat/sse-merge',
    preview_lines: claudeBoot('Implementing the delta-merge updater'),
    updated_at: new Date().toISOString(),
  },
  {
    name: 'ipc-astro',
    task_summary: 'Add Range support to the file streaming endpoint',
    status: 'waiting',
    dir: '/opt/projects/ipc',
    provider: 'claude',
    tokens: 12300,
    branch: 'fix/range-headers',
    preview_lines: [
      '● I can implement this two ways: a tower middleware',
      '  or inline in the handler. The middleware is reusable',
      '  but adds a dependency.',
      '',
      'Which approach do you want me to take?',
      '❯',
    ],
    updated_at: new Date().toISOString(),
  },
  {
    name: 'docs-writer',
    task_summary: 'Draft the M11 acceptance notes',
    status: 'active',
    dir: '/opt/projects/amux',
    provider: 'claude',
    tokens: 6400,
    branch: 'main',
    preview_lines: claudeBoot('Writing ACCEPTANCE.md for the tile component'),
    updated_at: new Date().toISOString(),
  },
  {
    name: 'cso-review',
    task_summary: 'Security audit of the WS auth handshake',
    status: 'waiting',
    dir: '/opt/projects/amux/server',
    provider: 'claude',
    tokens: 31900,
    branch: 'audit/ws-auth',
    preview_lines: [
      '● Found: token passed in the WS query string (§3.2.9).',
      '  This leaks to access logs and browser history.',
      '',
      '  Recommend first-frame {type:"auth"} instead.',
      '',
      'Apply the fix now? (y/n)',
      '❯',
    ],
    updated_at: new Date().toISOString(),
  },
  {
    name: 'build-runner',
    task_summary: 'Release build',
    status: 'active',
    dir: '/opt/projects/amux/server',
    provider: 'shell',
    tokens: 0,
    branch: 'main',
    preview_lines: shellTail('cargo build --release'),
    updated_at: new Date().toISOString(),
  },
  {
    name: 'qa-astro',
    task_summary: 'Run the overview QA pass',
    status: 'starting',
    dir: '/opt/projects/web',
    provider: 'claude',
    tokens: 800,
    branch: 'qa/overview',
    preview_lines: ['Booting agent…', 'tmux new-session -d -s amux-qa-astro', '❯'],
    updated_at: new Date().toISOString(),
  },
  {
    name: 'idle-1',
    task_summary: 'Refactor the board reducer',
    status: 'idle',
    dir: '/opt/projects/board',
    provider: 'claude',
    tokens: 22100,
    branch: 'refactor/board',
    preview_lines: claudeBoot('Done. The reducer is now pure and tested.'),
    updated_at: new Date(Date.now() - 9 * 60_000).toISOString(),
  },
  {
    name: 'idle-2',
    task_summary: 'Investigate the reconnect storm',
    status: 'idle',
    dir: '/opt/projects/amux',
    provider: 'claude',
    tokens: 15600,
    branch: 'fix/reconnect-jitter',
    preview_lines: [
      '● Added ±20% decorrelated jitter to the backoff.',
      '  delay = base * 2^n; jittered = delay/2 + rand(delay)',
      '',
      '  Verified across 50 simulated drops — no thundering herd.',
    ],
    updated_at: new Date(Date.now() - 23 * 60_000).toISOString(),
  },
  {
    name: 'long-name-session-with-a-really-long-title',
    task_summary:
      'A deliberately long chat summary that should truncate to a single line without breaking the title-row layout',
    status: 'idle',
    dir: '/opt/projects/edge',
    provider: 'claude',
    tokens: 103400,
    branch: 'feature/very-long-branch-name-here',
    preview_lines: claudeBoot('Truncation check'),
    updated_at: new Date(Date.now() - 41 * 60_000).toISOString(),
  },
  {
    name: 'errored-agent',
    task_summary: 'Migrate the snippets table',
    status: 'error',
    dir: '/opt/projects/db',
    provider: 'claude',
    tokens: 4200,
    branch: 'migrate/snippets',
    preview_lines: [
      '● Bash(sqlite3 amux.db < 0006.sql)',
      '  ⎿ Error: near "TABEL": syntax error',
      '',
      '  The migration failed. I stopped before touching data.',
    ],
    updated_at: new Date(Date.now() - 2 * 60_000).toISOString(),
  },
  {
    name: 'stopped-agent',
    task_summary: 'Nightly dependency bump',
    status: 'stopped',
    dir: '/opt/projects/deps',
    provider: 'shell',
    tokens: 0,
    branch: 'chore/deps',
    preview_lines: shellTail('bun update'),
    updated_at: new Date(Date.now() - 6 * 3_600_000).toISOString(),
  },
  {
    name: 'ghost-session',
    task_summary: 'Was reviewing the scheduler',
    status: 'error',
    dir: '/opt/projects/sched',
    provider: 'claude',
    tokens: 9100,
    branch: 'review/scheduler',
    missing: true,
    preview_lines: [],
    updated_at: new Date(Date.now() - 12 * 3_600_000).toISOString(),
  },
]
