// Mock tiles for the /dev/tiles verification page (DEV-only — never bundled
// into production; see App.tsx lazy import). Covers every status the tile
// renders so the visual critic can check all states in one screen.

import type { TileSession } from './types'

const claudeBoot = (task: string): string[] => [
  '● Read package.json (1 file)',
  `● ${task}`,
  '',
  '  Let me start by exploring the codebase structure to',
  '  understand how the existing modules fit together.',
  '',
  '● Bash(bun run build)',
  '  ⎿ tsc -b && vite build',
  '     ✓ 2243 modules transformed.',
  '     ✓ built in 245ms',
]

// ANSI-coloured twin of `claudeBoot` — exercises the `preview_ansi` colour path
// (DEV mock only). `E` is the ESC byte; SGR codes: 32 green, 33 yellow, 36 cyan,
// 90 grey, 1 bold, 0 reset. ~20 lines so the "Expanded text" hover (which
// surfaces up to ~20 lines vs the 6-line idle tail) is verifiable end-to-end.
const E = '\x1b'
const claudeBootAnsi = (task: string): string[] => [
  `${E}[32m●${E}[0m Read ${E}[36mpackage.json${E}[0m ${E}[90m(1 file)${E}[0m`,
  `${E}[32m●${E}[0m Read ${E}[36mtsconfig.json${E}[0m ${E}[90m(1 file)${E}[0m`,
  `${E}[32m●${E}[0m ${E}[1m${task}${E}[0m`,
  '',
  '  Let me start by exploring the codebase structure to',
  '  understand how the existing modules fit together.',
  '',
  `${E}[32m●${E}[0m ${E}[36mGrep${E}[0m(pattern: "useLiveTerm")`,
  `  ${E}[90m⎿${E}[0m Found ${E}[33m3${E}[0m files`,
  `     ${E}[90msrc/hooks/use-live-term.ts${E}[0m`,
  `     ${E}[90msrc/components/terminal/live-terminal.tsx${E}[0m`,
  '',
  `${E}[32m●${E}[0m ${E}[36mBash${E}[0m(bun run build)`,
  `  ${E}[90m⎿${E}[0m tsc -b && vite build`,
  `     ${E}[32m✓${E}[0m 2243 modules transformed.`,
  `     ${E}[32m✓${E}[0m built in ${E}[33m245ms${E}[0m`,
  '',
  `${E}[32m●${E}[0m All checks pass. ${E}[33mWarning:${E}[0m 1 chunk over 500 kB.`,
  `  ${E}[90m⎿${E}[0m Done — the build is green.`,
]

const shellTail = (cmd: string): string[] => [
  `$ ${cmd}`,
  'Compiling supermux-server v3.0.0',
  '   Compiling tokio v1.40.0',
  '   Compiling axum v0.7.5',
  '    Finished `release` profile [optimized]',
  '     Running `target/release/supermux-server`',
  'listening on 127.0.0.1:8823',
]

const shellTailAnsi = (cmd: string): string[] => [
  `${E}[1m$${E}[0m ${cmd}`,
  `${E}[32m   Compiling${E}[0m supermux-server v3.0.0`,
  `${E}[32m   Compiling${E}[0m tokio v1.40.0`,
  `${E}[32m   Compiling${E}[0m axum v0.7.5`,
  `${E}[32m    Finished${E}[0m \`release\` profile ${E}[90m[optimized]${E}[0m`,
  `${E}[32m     Running${E}[0m \`target/release/supermux-server\``,
  `${E}[36mlistening${E}[0m on 127.0.0.1:8823`,
]

export const MOCK_TILES: TileSession[] = [
  {
    // A Codex-provider session so the dev harness can review Codex-only
    // affordances (e.g. "Edit in native editor", which Codex opens with the
    // same Ctrl+G $EDITOR bridge as Claude). Visit /dev/focus/codex-app.
    name: 'codex-app',
    task_summary: 'Port the retry backoff to the exec-server transport',
    status: 'waiting',
    dir: '/opt/projects/codex-app',
    provider: 'codex',
    tokens: 21400,
    branch: 'feat/exec-backoff',
    preview_lines: [
      '› codex',
      '',
      '• Proposed patch: add decorrelated jitter to the retry loop.',
      '',
      '  Apply this change? (y/n)',
      '›',
    ],
    updated_at: new Date().toISOString(),
  },
  {
    name: 'web-app',
    task_summary: 'Wire the SSE delta merge into the sessions cache',
    status: 'active',
    dir: '/opt/projects/web-app',
    provider: 'claude',
    tokens: 48200,
    branch: 'feat/sse-merge',
    activity: '✎ use-sessions.ts',
    subagents: 3,
    preview_lines: claudeBoot('Implementing the delta-merge updater'),
    preview_ansi: claudeBootAnsi('Implementing the delta-merge updater'),
    updated_at: new Date().toISOString(),
  },
  {
    name: 'api-server',
    task_summary: 'Add Range support to the file streaming endpoint',
    status: 'waiting',
    dir: '/opt/projects/api-server',
    provider: 'claude',
    tokens: 12300,
    branch: 'fix/range-headers',
    preview_lines: [
      '● I can implement this two ways: a tower middleware',
      '  or inline in the handler. The middleware is reusable',
      '  but adds a dependency.',
      '',
      'Which approach do you want me to take?',
      '❯',
    ],
    updated_at: new Date().toISOString(),
  },
  {
    name: 'docs-writer',
    task_summary: 'Draft the upcoming acceptance notes',
    status: 'active',
    dir: '/opt/projects/supermux',
    provider: 'claude',
    tokens: 6400,
    branch: 'main',
    activity: '🤖 dispatching review agents',
    subagents: 5,
    preview_lines: claudeBoot('Writing acceptance notes for the tile component'),
    preview_ansi: claudeBootAnsi('Writing acceptance notes for the tile component'),
    updated_at: new Date().toISOString(),
  },
  {
    name: 'cso-review',
    task_summary: 'Security audit of the WS auth handshake',
    status: 'waiting',
    dir: '/opt/projects/supermux/server',
    provider: 'claude',
    tokens: 31900,
    branch: 'audit/ws-auth',
    preview_lines: [
      '● Found: token passed in the WS query string.',
      '  This leaks to access logs and browser history.',
      '',
      '  Recommend first-frame {type:"auth"} instead.',
      '',
      'Apply the fix now? (y/n)',
      '❯',
    ],
    updated_at: new Date().toISOString(),
  },
  {
    name: 'build-runner',
    task_summary: 'Release build',
    status: 'active',
    dir: '/opt/projects/supermux/server',
    provider: 'shell',
    tokens: 0,
    branch: 'main',
    preview_lines: shellTail('cargo build --release'),
    preview_ansi: shellTailAnsi('cargo build --release'),
    updated_at: new Date().toISOString(),
  },
  {
    name: 'qa-astro',
    task_summary: 'Run the overview QA pass',
    status: 'starting',
    dir: '/opt/projects/web',
    provider: 'claude',
    tokens: 800,
    branch: 'qa/overview',
    preview_lines: ['Booting agent…', 'tmux new-session -d -s supermux-qa-astro', '❯'],
    updated_at: new Date().toISOString(),
  },
  {
    name: 'idle-1',
    task_summary: 'Refactor the board reducer',
    status: 'idle',
    dir: '/opt/projects/board',
    provider: 'claude',
    tokens: 22100,
    branch: 'refactor/board',
    preview_lines: claudeBoot('Done. The reducer is now pure and tested.'),
    preview_ansi: claudeBootAnsi('Done. The reducer is now pure and tested.'),
    updated_at: new Date(Date.now() - 9 * 60_000).toISOString(),
  },
  {
    name: 'idle-2',
    task_summary: 'Investigate the reconnect storm',
    status: 'idle',
    dir: '/opt/projects/supermux',
    provider: 'claude',
    tokens: 15600,
    branch: 'fix/reconnect-jitter',
    preview_lines: [
      '● Added ±20% decorrelated jitter to the backoff.',
      '  delay = base * 2^n; jittered = delay/2 + rand(delay)',
      '',
      '  Verified across 50 simulated drops — no thundering herd.',
    ],
    updated_at: new Date(Date.now() - 23 * 60_000).toISOString(),
  },
  {
    name: 'long-name-session-with-a-really-long-title',
    task_summary:
      'A deliberately long chat summary that should truncate to a single line without breaking the title-row layout',
    status: 'idle',
    dir: '/opt/projects/edge',
    provider: 'claude',
    tokens: 103400,
    branch: 'feature/very-long-branch-name-here',
    preview_lines: claudeBoot('Truncation check'),
    updated_at: new Date(Date.now() - 41 * 60_000).toISOString(),
  },
  {
    name: 'errored-agent',
    task_summary: 'Migrate the snippets table',
    status: 'error',
    dir: '/opt/projects/db',
    provider: 'claude',
    tokens: 4200,
    branch: 'migrate/snippets',
    preview_lines: [
      '● Bash(sqlite3 supermux.db < 0006.sql)',
      '  ⎿ Error: near "TABEL": syntax error',
      '',
      '  The migration failed. I stopped before touching data.',
    ],
    updated_at: new Date(Date.now() - 2 * 60_000).toISOString(),
  },
  {
    name: 'stopped-agent',
    task_summary: 'Nightly dependency bump',
    status: 'stopped',
    dir: '/opt/projects/deps',
    provider: 'shell',
    tokens: 0,
    branch: 'chore/deps',
    preview_lines: shellTail('bun update'),
    updated_at: new Date(Date.now() - 6 * 3_600_000).toISOString(),
  },
  {
    name: 'ghost-session',
    task_summary: 'Was reviewing the scheduler',
    status: 'error',
    dir: '/opt/projects/sched',
    provider: 'claude',
    tokens: 9100,
    branch: 'review/scheduler',
    missing: true,
    preview_lines: [],
    updated_at: new Date(Date.now() - 12 * 3_600_000).toISOString(),
  },
]
